=== clappcom/szamlazzhuclient/xmlsamples/xmlszamla.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.szamlazz.hu/xmlszamla" xmlns:tns="http://www.szamlazz.hu/xmlszamla" elementFormDefault="qualified">

    <complexType name="vevoTipus">
        <sequence>
            <element name="nev" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="orszag" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="irsz" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="telepules" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="cim" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="email" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="sendEmail" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="adoszam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="adoszamEU" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="postazasiNev" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="postazasiOrszag" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="postazasiIrsz" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="postazasiTelepules" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="postazasiCim" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="vevoFokonyv" type="tns:vevoFokonyvTipus" maxOccurs="1" minOccurs="0"></element>            
            <element name="azonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="alairoNeve" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="telefonszam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="megjegyzes" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="vevoFokonyvTipus">
        <sequence>
            <element name="konyvelesDatum" type="date" maxOccurs="1" minOccurs="0"></element>
            <element name="vevoAzonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="vevoFokonyviSzam" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    
    <complexType name="eladoTipus">
        <sequence>
            <element name="bank" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="bankszamlaszam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="emailReplyto" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="emailTargy" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="emailSzoveg" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="alairoNeve" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    
    <complexType name="beallitasokTipus">
        <sequence>
            <element name="felhasznalo" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="jelszo" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="eszamla" type="boolean" maxOccurs="1" minOccurs="1"></element>
            <element name="kulcstartojelszo" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaLetoltes" type="boolean" maxOccurs="1" minOccurs="1"></element>
            <element name="szamlaLetoltesPld" type="int" maxOccurs="1" minOccurs="0"></element>
            <element name="valaszVerzio" type="int" maxOccurs="1" minOccurs="0"></element>
            <element name="aggregator" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>
    
    <complexType name="tetelTipus">
        <sequence>
            <element name="megnevezes" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="azonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="mennyiseg" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="mennyisegiEgyseg" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="nettoEgysegar" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="afakulcs" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="arresAfaAlap" type="double" maxOccurs="1" minOccurs="0"></element>                        
            <element name="nettoErtek" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="afaErtek" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="bruttoErtek" type="double" maxOccurs="1" minOccurs="1"></element>
            <element name="megjegyzes" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="tetelFokonyv" type="tns:tetelFokonyvTipus" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="tetelFokonyvTipus">
        <sequence>
            <element name="gazdasagiEsem" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="gazdasagiEsemAfa" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="arbevetelFokonyviSzam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="afaFokonyviSzam" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="fejlecTipus">
        <sequence>
            <element name="keltDatum" type="date" maxOccurs="1" minOccurs="1"></element>
            <element name="teljesitesDatum" type="date" maxOccurs="1" minOccurs="1"></element>
            <element name="fizetesiHataridoDatum" type="date" maxOccurs="1" minOccurs="1"></element>
            <element name="fizmod" type="string" maxOccurs="1" minOccurs="1"></element>
            <element name="penznem" type="string" maxOccurs="1"    minOccurs="1"></element>
            <element name="szamlaNyelve" type="tns:szamlaNyelveTipus" maxOccurs="1" minOccurs="1"></element>
            <element name="megjegyzes" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="arfolyamBank" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="arfolyam" type="double" maxOccurs="1" minOccurs="0"></element>
            <element name="rendelesSzam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="elolegszamla" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="vegszamla" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="helyesbitoszamla" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="helyesbitettSzamlaszam" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="dijbekero" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="logoExtra" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="szamlaszamElotag" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="fizetendoKorrekcio" type="double" maxOccurs="1" minOccurs="0"></element>
            <element name="fizetve" type="boolean" maxOccurs="1" minOccurs="0"></element>
            <element name="arresAfa" type="boolean" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <simpleType name="szamlaNyelveTipus">
        <restriction base="string">
            <enumeration value="hu"></enumeration>
            <enumeration value="en"></enumeration>
            <enumeration value="de"></enumeration>
            <enumeration value="it"></enumeration>
            <enumeration value="ro"></enumeration>
            <enumeration value="sk"></enumeration>
            <enumeration value="hr"></enumeration>
            <enumeration value="fr"></enumeration>
        </restriction>
    </simpleType>

    <complexType name="transoflexTipus">
        <sequence>
            <!-- a TOF-tól kapott 5 jegyű szám -->
            <element name="azonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="shipmentID" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="csomagszam" type="int" maxOccurs="1" minOccurs="0"></element>
            <element name="countryCode" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="zip" type="string" maxOccurs="1" minOccurs="0"></element>
            <element name="service" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="sprinterTipus">
        <sequence>
            <!-- Sprinterrel egyeztetett 3 karakteres rövidítés -->
            <element name="azonosito" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- Sprintertől kapott feladókód, 10 jegyű szám -->
            <element name="feladokod" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- Sprinteres iránykód, az a sprinter saját "irányítószáma", pl. "106" -->
            <element name="iranykod" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- Csomagok száma, ennyi fuvarlevél lesz a számlához összesen -->
            <element name="csomagszam" type="int" maxOccurs="1" minOccurs="0"></element>
            <!-- számlánként egyedi, 7-13 karakteres azonosító -->
            <element name="vonalkodPostfix" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- ez az 1 munkanapos szöveg, többnyire -->
            <element name="szallitasiIdo" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="pppTipus">
        <sequence>
            <!-- PPP-vel egyeztetett 3 karakteres rövidítés -->
            <element name="vonalkodPrefix" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- számlánként egyedi, maximum 7 karakteres azonosító -->
            <element name="vonalkodPostfix" type="string" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="fuvarlevelTipus">
        <sequence>
            <!-- TODO az "uticel" nem használt, 2014.05.30. után eltávolítandó, helyette a sprinter/iranykod mező használandó -->
            <element name="uticel" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- TOF, PPP, SPRINTER lehet az értéke, ha nincs fuvarlevél, akkor nem kell megadni -->
            <element name="futarSzolgalat" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- Általános vonalkód megadási lehetőség, ha az alágban nem adjuk meg az adott futárszolgálat 
                 vonalkódjának előállításához szükséges adatokat akkor ezt használja a rendszer. -->
            <element name="vonalkod" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- A fuvarlevélen ez a megjegyzés jelenik meg. -->
            <element name="megjegyzes" type="string" maxOccurs="1" minOccurs="0"></element>
            <!-- Trans-O-Flex futárszolgálat esetén feltöltendő csomópont -->
            <element name="tof" type="tns:transoflexTipus" maxOccurs="1" minOccurs="0"></element>
            <!-- PickPackPoint-ra szállítás esetén kitöltendő csomópont -->
            <element name="ppp" type="tns:pppTipus" maxOccurs="1" minOccurs="0"></element>
            <!-- Sprinter futárszolgálat esetén feltöltendő csomópont -->
            <element name="sprinter" type="tns:sprinterTipus" maxOccurs="1" minOccurs="0"></element>
        </sequence>
    </complexType>

    <element name="xmlszamla">
	    <complexType>
	        <sequence>
	            <element name="beallitasok" type="tns:beallitasokTipus" maxOccurs="1" minOccurs="1"></element>
	            <element name="fejlec" type="tns:fejlecTipus" maxOccurs="1" minOccurs="1"></element>
	            <element name="elado" type="tns:eladoTipus" maxOccurs="1" minOccurs="1"></element>
	            <element name="vevo" type="tns:vevoTipus" maxOccurs="1" minOccurs="1"></element>
	            <element name="fuvarlevel" type="tns:fuvarlevelTipus" maxOccurs="1" minOccurs="0"></element>
	            <element name="tetelek" type="tns:tetelekTipus" maxOccurs="1" minOccurs="1"></element>
	        </sequence>
	    </complexType>
    </element>

    <complexType name="tetelekTipus">
        <sequence>
            <element name="tetel" type="tns:tetelTipus" maxOccurs="unbounded" minOccurs="1"></element>
        </sequence>
    </complexType>
</schema>

=== clappcom/szamlazzhuclient/commentedsample.xml
<?xml version="1.0" encoding="UTF-8"?> <xmlszamla xmlns="http://www.szamlazz.hu/xmlszamla" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.szamlazz.hu/xmlszamla xmlszamla.xsd ">
 <beallitasok>
    <felhasznalo>teszt01</felhasznalo> <!-- a Számlázz.hu-s felhasználó -->
    <jelszo>teszt01</jelszo> <!-- a Számlázz.hu-s felhasználó jelszava -->
    <eszamla>true</eszamla> <!-- „true” ha e-számlát kell készíteni -->
    <szamlaLetoltes>true</szamlaLetoltes> <!-- „true” ha a válaszban meg szeretnénk kapni az elkészült PDF számlát -->
    <valaszVerzio>1</valaszVerzio> <!-- 1: egyszerű szöveges válaszüzenetet vagy pdf-et ad vissza. 2: xml válasz, ha kérte a pdf-et az base64 kódolással benne van az xml-ben. -->
</beallitasok>
 <fejlec>
    <keltDatum>2010-09-12</keltDatum> <!-- a dátum formátum kötött -->
    <teljesitesDatum>2010-09-10</teljesitesDatum>
    <fizetesiHataridoDatum>2010-09-20</fizetesiHataridoDatum>
    <fizmod>Átutalás</fizmod> <!-- értékkészlet: böngészőből történő számlakészítés során látható -->
    <penznem>HUF</penznem> <!-- értékkészlet: böngészőből történő számlakészítés során látható -->
    <szamlaNyelve>hu</szamlaNyelve> <!-- lehet: de, en, it -->
    <megjegyzes>Számla megjegyzés</megjegyzes>
    <arfolyamBank>MNB</arfolyamBank> <!-- devizás számla esetén meg kell adni, hogy melyik bank árfolyamával számoltuk a számlán a forintos ÁFA értéket -->
    <arfolyam>0.0</arfolyam> <!-- devizás számla esetén meg kell adni, hogy melyik bank árfolyamával számoltuk a számlán a forintos ÁFA értéket -->
    <rendelesSzam></rendelesSzam>
    <elolegszamla>false</elolegszamla>
    <vegszamla>false</vegszamla>
    <helyesbitoszamla>false</helyesbitoszamla>
    <helyesbitettSzamlaszam />
    <dijbekero>false</dijbekero>
    <szamlaszamElotag>Kérem töltse ki!</szamlaszamElotag> <!-- a számlatömb menüben található lista valamelyik engedélyezett sorának számlaszám előtag értéke-->
    <fizetve>true</fizetve> <!-- a számla elkészítését követően azonnal kifizetettként adminisztrálódik -->
</fejlec>
 <elado> <!-- Az eladó adatai, az itt nem szereplő adatokat a Számlázz.hu felhasználói fiókból veszi a rendszer -->
    <bank>BB</bank>
    <bankszamlaszam>11111111-22222222-33333333</bankszamlaszam>
    <emailReplyto></emailReplyto>
    <emailTargy>Számla értesítő</emailTargy>
    <emailSzoveg>Fizesse ki a számlát, különben mindenkori ...</emailSzoveg>
    <alairoNeve>Eladó Aláírója</alairoNeve><!-- Nem kötelező adat. Ha a beállítások oldalon be van kapcsolva, akkor ez a név megjelenik az aláírásra szolgáló vonal alatt -->
</elado>
 <vevo> <!-- Vevő adatai -->
    <nev>Kovacs Bt.</nev>
    <irsz>2030</irsz>
    <telepules>Érd</telepules>
    <cim>Tárnoki út 23.</cim>
    <!-- <email></email> --> <!-- ha meg van adva, akkor erre az email címre kiküldi a számlát a Számlázz.hu TESZT FIÓK ESETÉN BIZTONSÁGI OKOKBÓL NEM KÜLD A RENDSZER EMAILT. AZ EMAIL KÜLDÉS E-SZÁMLA ÉS PRÉMIUM CSOMAG ESETÉN MŰKÖDIK. →
    <!--sendEmail>false</sendEmail--> <!-->kérheti, hogy érvényes email cím esetén mégse küldje el a Számla Agent a számlaértesítő email-t.<-->
    <adoszam>12345678-1-42</adoszam>
    <postazasiNev>Kovács Bt. postázási név</postazasiNev> <!-- a postázási adatok nem kötelezők -->
    <postazasiIrsz>2040</postazasiIrsz>
    <postazasiTelepules>Budaörs</postazasiTelepules>
    <postazasiCim>Szivárvány utca 8. VI.em. 42.</postazasiCim>
    <alairoNeve>Vevő Aláírója</alairoNeve><!-- Nem kötelező adat. Ha a beállítások oldalon be van kapcsolva, akkor ez a név megjelenik az aláírásra szolgáló vonal alatt -->
    <telefonszam>Tel:+3630-555-55-55, Fax:+3623-555-555</telefonszam>
    <megjegyzes>A portáról felszólni a 214-es mellékre.</megjegyzes>
</vevo>
    <fuvarlevel><!-- Ez nem kötelező szekció, ha fuvarlevelet szeretne nyomtatni kérjük vegye fel a kapcsolatot az ügyfélszolgálattal az info@szamlazz.hu email címen. -->
    <uticel></uticel>
    <futarSzolgalat></futarSzolgalat>
    </fuvarlevel>
<tetelek> <!-- a számla tételei -->
    <tetel>
        <megnevezes>Elado izé</megnevezes>
        <mennyiseg>1.0</mennyiseg>
        <mennyisegiEgyseg>db</mennyisegiEgyseg>
        <nettoEgysegar>10000</nettoEgysegar>
        <afakulcs>25</afakulcs> <!-- ua. adható meg, mint a számlakészítés oldalon -->
        <nettoErtek>10000.0</nettoErtek>
        <afaErtek>2500.0</afaErtek>
        <bruttoErtek>12500.0</bruttoErtek>
        <megjegyzes>tétel megjegyzés 1</megjegyzes>
    </tetel>
    <tetel>
        <megnevezes>Elado izé 2</megnevezes>
        <mennyiseg>2.0</mennyiseg>
        <mennyisegiEgyseg>db</mennyisegiEgyseg>
        <nettoEgysegar>10000</nettoEgysegar>
        <afakulcs>25</afakulcs>
        <nettoErtek>20000.0</nettoErtek>
        <afaErtek>5000.0</afaErtek>
        <bruttoErtek>25000.0</bruttoErtek>
        <megjegyzes>tétel megjegyzés 2</megjegyzes>
     </tetel>
 </tetelek> 
</xmlszamla>

=== clappcom/szamlazzhuclient/xmlsamples/xmlszamla.xml
<?xml version="1.0" encoding="UTF-8"?>
<xmlszamla xmlns="http://www.szamlazz.hu/xmlszamla" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.szamlazz.hu/xmlszamla xmlszamla.xsd ">
  <beallitasok>
    <felhasznalo>Kérem töltse ki!</felhasznalo>
    <jelszo>Kérem töltse ki!</jelszo>
    <eszamla>false</eszamla>
    <kulcstartojelszo></kulcstartojelszo>
    <szamlaLetoltes>true</szamlaLetoltes>
    <szamlaLetoltesPld>2</szamlaLetoltesPld>
    <valaszVerzio>1</valaszVerzio>
    <aggregator></aggregator>
  </beallitasok>
  <fejlec>
    <keltDatum>2012-04-12</keltDatum>
    <teljesitesDatum>2012-04-10</teljesitesDatum>
    <fizetesiHataridoDatum>2012-04-20</fizetesiHataridoDatum>
    <fizmod>Átutalás</fizmod>
    <penznem>Ft</penznem>
    <szamlaNyelve>hu</szamlaNyelve>
    <megjegyzes>Számla megjegyzés</megjegyzes>
    <arfolyamBank>MNB</arfolyamBank>
    <arfolyam>0.0</arfolyam>
    <rendelesSzam></rendelesSzam>
    <elolegszamla>false</elolegszamla>
    <vegszamla>false</vegszamla>
    <dijbekero>false</dijbekero>
    <szamlaszamElotag>Kérem töltse ki, vagy hagyja ki!</szamlaszamElotag>
    <fizetve>true</fizetve>
  </fejlec>
  <elado>
    <bank>OBER</bank>
    <bankszamlaszam>11111111-22222222-33333333</bankszamlaszam>
    <emailReplyto></emailReplyto>
    <emailTargy>Számla értesítő</emailTargy>
    <emailSzoveg>Fizesse ki a számlát, különben a mindenkori banki kamat</emailSzoveg>
    <!-- <alairoNeve>Eladó Aláírója</alairoNeve> -->
  </elado>
  <vevo>
    <nev>Kovacs Bt.</nev>
    <irsz>2030</irsz>
    <telepules>Érd</telepules>
    <cim>Tárnoki út 23.</cim>
    <!-- <email>vevoneve@example.org</email> -->
    <!-- <sendEmail>true</sendEmail> -->
    <adoszam>12345678-1-42</adoszam>
    <postazasiNev>Kovács Bt. postázási név</postazasiNev>
    <postazasiIrsz>2040</postazasiIrsz>
    <postazasiTelepules>Budaörs</postazasiTelepules>
    <postazasiCim>Szivárvány utca 8. VI.em. 82.</postazasiCim>
    <!-- <alairoNeve>Vevő Aláírója</alairoNeve> -->
    <!-- <azonosito></azonosito> -->
    <!-- <telefonszam>+3630-555-55-55, Fax:+3623-555-555</telefonszam> -->
    <!-- <megjegyzes>A portáról felszólni a 214-es mellékre.</megjegyzes> -->
  </vevo><!-- Ez nem kötelező szekció, ha fuvarlevelet szeretne nyomtatni kérjük vegye 
              fel a kapcsolatot az ügyfélszolgálattal az info@szamlazz.hu email címen.
  <fuvarlevel>
    <uticel>106</uticel>
    <futarSzolgalat>PPP</futarSzolgalat>
  </fuvarlevel> -->
  <tetelek>
    <tetel>
      <megnevezes>Elado izé</megnevezes>
      <mennyiseg>1.0</mennyiseg>
      <mennyisegiEgyseg>db</mennyisegiEgyseg>
      <nettoEgysegar>10000</nettoEgysegar>
      <afakulcs>27</afakulcs>
      <nettoErtek>10000.0</nettoErtek>
      <afaErtek>2700.0</afaErtek>
      <bruttoErtek>12700.0</bruttoErtek>
      <megjegyzes>tétel megjegyzés 1</megjegyzes>
    </tetel>
    <tetel>
      <megnevezes>Elado izé 2</megnevezes>
      <mennyiseg>2.0</mennyiseg>
      <mennyisegiEgyseg>db</mennyisegiEgyseg>
      <nettoEgysegar>10000</nettoEgysegar>
      <afakulcs>27</afakulcs>
      <nettoErtek>20000.0</nettoErtek>
      <afaErtek>5400.0</afaErtek>
      <bruttoErtek>25400.0</bruttoErtek>
      <megjegyzes>tétel megjegyzés 2</megjegyzes>
    </tetel>
  </tetelek>
</xmlszamla>
